#!/usr/bin/env bash

echo "Creating database webApp..."
pgmgr db create

echo "Running migrations..."
pgmgr db migrate

echo "Creating database webApp-test"
pgmgr -c ".pgmgr.test.json" db create

echo "Running migration on postgres://john@localhost:5432/webApp-test?sslmode=disable..."
pgmgr -c ".pgmgr.test.json" db migrate
